ITory/Models/Tipo_Inventario.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_Inventario()
        {
            this.Articulo = new HashSet<Articulo>();
            this.Asiento_Contable = new HashSet<Asiento_Contable>();
        }
    
        public int idTipoInventario { get; set; }
        public string Nombre { get; set; }
        public string Cuenta_Contable { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articulo> Articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiento_Contable> Asiento_Contable { get; set; }
    }
}

ITory/Controllers/Tipo_InventarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ITory.Models;

namespace ITory.Controllers
{
    public class Tipo_InventarioController : Controller
    {
        private InventarioDBEntities db = new InventarioDBEntities();

        // GET: Tipo_Inventario
        public ActionResult Index()
        {
            return View(db.Tipo_Inventario.ToList());
        }

        // GET: Tipo_Inventario/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tipo_Inventario tipo_Inventario = db.Tipo_Inventario.Find(id);
            if (tipo_Inventario == null)
            {
                return HttpNotFound();
            }
            return View(tipo_Inventario);
        }

        // GET: Tipo_Inventario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tipo_Inventario/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idTipoInventario,Nombre,Cuenta_Contable,Estado")] Tipo_Inventario tipo_Inventario)
        {
            if (ModelState.IsValid)
            {
                db.Tipo_Inventario.Add(tipo_Inventario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tipo_Inventario);
        }

        // GET: Tipo_Inventario/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tipo_Inventario tipo_Inventario = db.Tipo_Inventario.Find(id);
            if (tipo_Inventario == null)
            {
                return HttpNotFound();
            }
            return View(tipo_Inventario);
        }

        // POST: Tipo_Inventario/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idTipoInventario,Nombre,Cuenta_Contable,Estado")] Tipo_Inventario tipo_Inventario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipo_Inventario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipo_Inventario);
        }

        // GET: Tipo_Inventario/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tipo_Inventario tipo_Inventario = db.Tipo_Inventario.Find(id);
            if (tipo_Inventario == null)
            {
                return HttpNotFound();
            }
            return View(tipo_Inventario);
        }

        // POST: Tipo_Inventario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tipo_Inventario tipo_Inventario = db.Tipo_Inventario.Find(id);
            db.Tipo_Inventario.Remove(tipo_Inventario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ITory/Views/Tipo_Inventario/Create.cshtml
@model ITory.Models.Tipo_Inventario

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tipo_Inventario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cuenta_Contable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cuenta_Contable, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cuenta_Contable, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ITory/Views/Tipo_Inventario/Delete.cshtml
@model ITory.Models.Tipo_Inventario

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tipo_Inventario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cuenta_Contable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cuenta_Contable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ITory/Views/Tipo_Inventario/Details.cshtml
@model ITory.Models.Tipo_Inventario

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tipo_Inventario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cuenta_Contable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cuenta_Contable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idTipoInventario }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ITory/Views/Tipo_Inventario/Edit.cshtml
@model ITory.Models.Tipo_Inventario

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tipo_Inventario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idTipoInventario)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cuenta_Contable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cuenta_Contable, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cuenta_Contable, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ITory/Views/Tipo_Inventario/Index.cshtml
@model IEnumerable<ITory.Models.Tipo_Inventario>

@{
    ViewBag.Title = "Inventarios";
}

<div class="card ">
    <div class="card-header container-fluid text-white" style="background-color:#ffb034">
        <div class="row">
            <div class="col-md-9">
                <h3>Tipos de inventarios</h3>
            </div>
            <div class="col-md" style="padding-top:10px;">
                <div class="float-right">
                    <form method="get" class="form-inline d-flex justify-content-center md-form form-sm mt-0">
                        <input class="form-control form-control-sm ml-3 w-75" name="Criterio" id="Criterio" type="text" placeholder="Search"
                               aria-label="Search">
                    </form>
                </div>
            </div>
            <div class="col-md" style="padding-top:10px;">
                <div class="float-right">

                    <a class="btn btn-light" href="@Url.Action("Create", "Tipo_Inventario")"><i class="glyphicon glyphicon-plus"></i>Añadir</a>
                </div>
            </div>

        </div>
    </div>
    <div class="card-body">
        <table class="table table-striped table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cuenta_Contable)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Estado)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cuenta_Contable)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Estado)
                    </td>
                    <td>
                        <a class="btn btn-primary btn-sm " title="Editar" href="@Url.Action("Edit", "Tipo_Inventario", new { id=item.idTipoInventario})"><i class="glyphicon glyphicon-edit"></i> </a>
                        <a class="btn btn-info btn-sm " title="Detalles" href="@Url.Action("Details", "Tipo_Inventario", new { id = item.idTipoInventario })"><i class="glyphicon glyphicon-eye-open"></i> </a>
                        <a class="btn btn-danger btn-sm " title="Eliminar" href="@Url.Action("Delete", "Tipo_Inventario", new { id=item.idTipoInventario})"><i class="glyphicon glyphicon-trash"></i> </a>
                    </td>
                </tr>
            }

        </table>
</div>
</div>