ITory/Controllers/Asiento_ContableController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ITory.Models;

namespace ITory.Controllers
{
    public class Asiento_ContableController : Controller
    {
        private InventarioDBEntities db = new InventarioDBEntities();

        // GET: Asiento_Contable
        public ActionResult Index()
        {
            var asiento_Contable = db.Asiento_Contable.Include(a => a.Tipo_Inventario);
            return View(asiento_Contable.ToList());
        }

        // GET: Asiento_Contable/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asiento_Contable asiento_Contable = db.Asiento_Contable.Find(id);
            if (asiento_Contable == null)
            {
                return HttpNotFound();
            }
            return View(asiento_Contable);
        }

        // GET: Asiento_Contable/Create
        public ActionResult Create()
        {
            ViewBag.idTipoInventario = new SelectList(db.Tipo_Inventario, "idTipoInventario", "Nombre");
            return View();
        }

        // POST: Asiento_Contable/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idAsiento,Descripcion,idTipoInventario,Cuenta_Contable,Tipo_Movimiento,Fecha_Asiento,Monto,Estado")] Asiento_Contable asiento_Contable)
        {
            if (ModelState.IsValid)
            {
                db.Asiento_Contable.Add(asiento_Contable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idTipoInventario = new SelectList(db.Tipo_Inventario, "idTipoInventario", "Nombre", asiento_Contable.idTipoInventario);
            return View(asiento_Contable);
        }

        // GET: Asiento_Contable/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asiento_Contable asiento_Contable = db.Asiento_Contable.Find(id);
            if (asiento_Contable == null)
            {
                return HttpNotFound();
            }
            ViewBag.idTipoInventario = new SelectList(db.Tipo_Inventario, "idTipoInventario", "Nombre", asiento_Contable.idTipoInventario);
            return View(asiento_Contable);
        }

        // POST: Asiento_Contable/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idAsiento,Descripcion,idTipoInventario,Cuenta_Contable,Tipo_Movimiento,Fecha_Asiento,Monto,Estado")] Asiento_Contable asiento_Contable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(asiento_Contable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idTipoInventario = new SelectList(db.Tipo_Inventario, "idTipoInventario", "Nombre", asiento_Contable.idTipoInventario);
            return View(asiento_Contable);
        }

        // GET: Asiento_Contable/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asiento_Contable asiento_Contable = db.Asiento_Contable.Find(id);
            if (asiento_Contable == null)
            {
                return HttpNotFound();
            }
            return View(asiento_Contable);
        }

        // POST: Asiento_Contable/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Asiento_Contable asiento_Contable = db.Asiento_Contable.Find(id);
            db.Asiento_Contable.Remove(asiento_Contable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ITory/Views/Asiento_Contable/Create.cshtml
@model ITory.Models.Asiento_Contable

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Asiento_Contable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idTipoInventario, "idTipoInventario", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idTipoInventario", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idTipoInventario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cuenta_Contable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cuenta_Contable, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cuenta_Contable, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo_Movimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tipo_Movimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tipo_Movimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_Asiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha_Asiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha_Asiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Monto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Monto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Monto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ITory/Views/Asiento_Contable/Delete.cshtml
@model ITory.Models.Asiento_Contable

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Asiento_Contable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cuenta_Contable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cuenta_Contable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo_Movimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo_Movimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha_Asiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha_Asiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Monto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo_Inventario.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo_Inventario.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ITory/Views/Asiento_Contable/Details.cshtml
@model ITory.Models.Asiento_Contable

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Asiento_Contable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cuenta_Contable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cuenta_Contable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo_Movimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo_Movimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha_Asiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha_Asiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Monto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo_Inventario.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo_Inventario.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idAsiento }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ITory/Views/Asiento_Contable/Edit.cshtml
@model ITory.Models.Asiento_Contable

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Asiento_Contable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idAsiento)

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idTipoInventario, "idTipoInventario", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idTipoInventario", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idTipoInventario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cuenta_Contable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cuenta_Contable, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cuenta_Contable, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo_Movimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tipo_Movimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tipo_Movimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_Asiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha_Asiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha_Asiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Monto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Monto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Monto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ITory/Views/Asiento_Contable/Index.cshtml
@model IEnumerable<ITory.Models.Asiento_Contable>

@{
    ViewBag.Title = "Asientos contables";
}

<div class="card ">
    <div class="card-header container-fluid text-white" style="background-color:#ffb034">
        <div class="row">
            <div class="col-md-9">
                <h3>Asientos Contables</h3>
            </div>
            <div class="col-md" style="padding-top:10px;">
                <div class="float-right">
                    <form method="get" class="form-inline d-flex justify-content-center md-form form-sm mt-0">
                        <input class="form-control form-control-sm ml-3 w-75" name="Criterio" id="Criterio" type="text" placeholder="Search"
                               aria-label="Search">
                    </form>
                </div>
            </div>
            <div class="col-md" style="padding-top:10px;">
                <div class="float-right">

                    <a class="btn btn-light" href="@Url.Action("Create", "Asiento_Contable")"><i class="glyphicon glyphicon-plus"></i>Añadir</a>
                </div>
            </div>

        </div>
    </div>
    <div class="card-body">
        <table class="table table-striped table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Descripcion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cuenta_Contable)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tipo_Movimiento)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Fecha_Asiento)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Monto)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Estado)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tipo_Inventario.Nombre)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cuenta_Contable)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tipo_Movimiento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fecha_Asiento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Monto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Estado)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tipo_Inventario.Nombre)
                    </td>
                    <td>
                        <a class="btn btn-primary btn-sm " title="Editar" href="@Url.Action("Edit", "Asiento_Contable", new { id=item.idAsiento})"><i class="glyphicon glyphicon-edit"></i> </a>
                        <a class="btn btn-info btn-sm " title="Detalles" href="@Url.Action("Details", "Asiento_Contable", new { id=item.idAsiento})"><i class="glyphicon glyphicon-eye-open"></i> </a>
                        <a class="btn btn-danger btn-sm " title="Eliminar" href="@Url.Action("Delete", "Asiento_Contable", new { id=item.idAsiento})"><i class="glyphicon glyphicon-trash"></i> </a>
                    </td>
                </tr>
            }

        </table>
</div>
</div>